public enum ErrorCode {
    NO_ERROR(0),
    INVALID_MESSAGE_LENGTH(1),
    INVALID_COMMAND_LENGTH(2),
    INVALID_COMMAND_ID(3),
    INVALID_BIND_STATUS(4),
    BIND_ATTEMPTED_WHEN_ALREADY_BOUND(5),
    INVALID_PRIORITY_FLAG(6),
    INVALID_REGISTERED_DELIVERY_FLAG(7),
    SMSC_SYSTEM_ERROR(8),
    INVALID_SOURCE_ADDRESS(10),
    INVALID_DESTINATION_ADDRESS(11),
    INVALID_MESSAGE_ID(12),
    GENERIC_BIND_FAILURE(13),
    INVALID_PASSWORD(14),
    INVALID_SYSTEM_ID(15),
    CANCEL_FAILURE(17),
    REPLACE_FAILURE(19),
    TOO_MANY_MESSAGES_IN_QUEUE_AT_PRESENT(20),
    INVALID_SERVICES_TYPE(22),
    INVALID_NUMBER_OF_DESTINATION_ADDRESSES(51),
    INVALID_NAME(52),
    INVALID_DESTINATION_FLAG_OPTION(64),
    INVALID_VALUE_FOR_SUBMIT_WITH_REPLACE_OPTION(66),
    INVALID_VALUE_FOR_ESM_CLASS_FIELD(67),
    CANNOT_SUBMIT_TO_A_DISTRIBUTION_LIST(68),
    GENERIC_SUBMISSION_FAILURE(69),
    INVALID_TYPE_OF_NUMBER_FOR_SOURCE(72),
    INVALID_NUMBERING_PLAN_INDICATOR_FOR_SOURCE(73),
    INVALID_TYPE_OF_NUMBER_FOR_DESTINATION(74),
    INVALID_NUMBERING_PLAN_INDICATOR_FOR_DESTINATION(75),
    INVALID_ESM_TYPE(77),
    INVALID_SUBMIT_WITH_REPLACE_FLAG_OPTION(78),
    INVALID_NUMBER_OF_MESSAGES_SPECIFIED_FOR_QUERY_LAST_MSGS_PRIMITIVE(85),
    SMSC_IS_THROTTLING_INBOUND_MESSAGES(88),
    INVALID_VALIDITY_DATE(98),
    QUOTA_VIOLATION_ADD_CREDIT_TO_ACCOUNT(103),
    INVALID_OPTIONAL_PARAMETER_LENGTH(194),
    MISSING_OPTIONAL_PARAMETER(195),
    INVALID_OPTIONAL_PARAMETER_VALUE(196),
    GENERIC_DELIVERY_FAILURE(254),
    UNKNOWN_ERROR(255);

    private final int errorCode;

    ErrorCode(final int errorCode) {
        this.errorCode = errorCode;
    }

    public int getErrorCode() {
        return errorCode;
    }
}
